src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OneToMany;
use Symfony\Component\Serializer\Annotation\Ignore;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CarRepository::class)
 */
class Car
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer", length=128, options={"unsigned": true})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer", length=4)
     * @Assert\Range(
     *     max="now year",
     *     min=1850
     * )
     */
    private $manufactured;

    /**
     * @OneToMany(targetEntity="App\Entity\CarReview", mappedBy="car")
     */
    private $reviews;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $generation;

    /**
     * @ORM\Column(type="string", length=3)
     * @Assert\Choice({"FWD", "RWD", "AWD"})
     */
    private $driven_axle;

    /**
     * @ORM\Column(type="integer", length=2)
     */
    private $seat_count;

    /**
     * @ORM\ManyToOne(targetEntity=Manufacturer::class, inversedBy="cars")
     * @ORM\JoinColumn(nullable=false)
     */
    private $manufacturer;

    /**
     * @ORM\ManyToOne(targetEntity=BodyStyle::class, inversedBy="cars")
     * @ORM\JoinColumn(nullable=false)
     */
    private $body_style;

    /**
     * @ORM\ManyToOne(targetEntity=Engine::class, inversedBy="cars")
     * @ORM\JoinColumn(nullable=false)
     */
    private $engine;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="cars")
     * @ORM\JoinColumn(nullable=false)
     */
    private $added_by;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="car", orphanRemoval=true)
     * @Ignore()
     */
    private $images;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->reviews = new ArrayCollection();
    }

    public function getReviews()
    {
        return $this->reviews;
    }

    public function removeReview(CarReview $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getCar() === $this) {
                $review->setCar(null);
            }
        }

        return $this;
    }

    public function addReview(CarReview $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setCar($this);
        }

        return $this;
    }

    public function getReviewIndex(): float
    {
        $sum = 0;
        $count = 0;
        foreach ($this->getReviews() as $review) {
            $sum += $review->getValue();
            $count++;
        }
        if ($count === 0) return 0;
        return ($sum/$count);
    }


    public function getId(): ?int
    {
        return $this->id;
    }


    public function getGeneration(): ?string
    {
        return $this->generation;
    }

    public function setGeneration(?string $generation): self
    {
        $this->generation = $generation;

        return $this;
    }

    public function getDrivenAxle(): ?string
    {
        return $this->driven_axle;
    }

    public function setDrivenAxle(string $driven_axle): self
    {
        $this->driven_axle = $driven_axle;

        return $this;
    }

    public function getSeatCount(): ?int
    {
        return $this->seat_count;
    }

    public function setSeatCount(int $seat_count): self
    {
        $this->seat_count = $seat_count;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getManufacturer(): ?Manufacturer
    {
        return $this->manufacturer;
    }

    public function setManufacturer(?Manufacturer $manufacturer): self
    {
        $this->manufacturer = $manufacturer;

        return $this;
    }

    public function getBodyStyle(): ?BodyStyle
    {
        return $this->body_style;
    }

    public function setBodyStyle(?BodyStyle $body_style): self
    {
        $this->body_style = $body_style;

        return $this;
    }

    public function getEngine(): ?Engine
    {
        return $this->engine;
    }

    public function setEngine(?Engine $engine): self
    {
        $this->engine = $engine;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getManufactured()
    {
        return $this->manufactured;
    }

    /**
     * @param mixed $manufactured
     */
    public function setManufactured($manufactured): void
    {
        $this->manufactured = $manufactured;
    }

    public function getAddedBy(): ?User
    {
        return $this->added_by;
    }

    public function setAddedBy(?User $added_by): self
    {
        $this->added_by = $added_by;

        return $this;
    }

    public function __toString(): string
    {
        return $this->manufacturer->getName() . ' ' . $this->getName();
    }

    /**
     * @return Collection<int, Image>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setCar($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getCar() === $this) {
                $image->setCar(null);
            }
        }

        return $this;
    }
}

src/Entity/Engine.php
<?php

namespace App\Entity;

use App\Repository\EngineRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EngineRepository::class)
 */
class Engine
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(
     *     type="integer",
     *     length=128,
     *     options={"unsigned": true})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $size;

    /**
     * @ORM\Column(type="integer", length=2)
     */
    private $number_of_cylinders;

    /**
     * @ORM\Column(type="integer")
     */
    private $max_power;

    /**
     * @ORM\Column(type="integer")
     */
    private $max_torque;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $aspiration;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $fuel;

    /**
     * @ORM\OneToMany(targetEntity=Car::class, mappedBy="engine")
     */
    private $cars;

    public function __construct()
    {
        $this->cars = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSize(): ?int
    {
        return $this->size;
    }

    public function setSize(int $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getNumberOfCylinders(): ?int
    {
        return $this->number_of_cylinders;
    }

    public function setNumberOfCylinders(int $number_of_cylinders): self
    {
        $this->number_of_cylinders = $number_of_cylinders;

        return $this;
    }

    public function getMaxPower(): ?int
    {
        return $this->max_power;
    }

    public function setMaxPower(int $max_power): self
    {
        $this->max_power = $max_power;

        return $this;
    }

    public function getMaxTorque(): ?int
    {
        return $this->max_torque;
    }

    public function setMaxTorque(int $max_torque): self
    {
        $this->max_torque = $max_torque;

        return $this;
    }

    public function getAspiration(): ?string
    {
        return $this->aspiration;
    }

    public function setAspiration(string $aspiration): self
    {
        $this->aspiration = $aspiration;

        return $this;
    }

    public function __toString()
    {
        return ($this->name ? $this->name . ' ' : '') . $this->fuel . ' ' . $this->getAspiration() . ' ' . $this->size . 'cm³';
    }

    public function getFuel(): ?string
    {
        return $this->fuel;
    }

    public function setFuel(string $fuel): self
    {
        $this->fuel = $fuel;

        return $this;
    }

    /**
     * @return Collection<int, Car>
     */
    public function getCars(): Collection
    {
        return $this->cars;
    }

    public function addCar(Car $car): self
    {
        if (!$this->cars->contains($car)) {
            $this->cars[] = $car;
            $car->setEngine($this);
        }

        return $this;
    }

    public function removeCar(Car $car): self
    {
        if ($this->cars->removeElement($car)) {
            // set the owning side to null (unless already changed)
            if ($car->getEngine() === $this) {
                $car->setEngine(null);
            }
        }

        return $this;
    }


}

templates/components/cards/car.html.twig
{% if dbal is not defined %}
    {% set dbal = false %}
{% endif %}
<div class="card">
    {% if car.images is defined and car.images is not empty %}
        <div class="p-1">
            <img src="{{ upload_image_dir }}/{% if dbal %}{{ random(car.images).file_name }}{% else %}{{ random(car.images).fileName }}{% endif %}"
                 class="card-car-image" alt="{{ car.name }}">
        </div>

    {% else %}
        <div class="card-car-icon p-1">
            <i class="fa-solid fa-car"></i>
        </div>
    {% endif %}
    <div class="card-body">
        <div class="card-title d-flex justify-content-between">
            <a href="{{ path('details.car', { 'id': car.id }) }}">
                <h5>
                    {% if dbal %}
                        {{ car.manufacturer_name }}
                    {% else %}
                        {{ car.manufacturer.name }}
                    {% endif %}
                    {{ car.name }}
                </h5>
            </a>
            <span>
                {% if dbal %}
                    <p>{{ (50*(car.review/car.review_count+1))|number_format('2') }} %</p>
                {% else %}
                    <p>{{ (50*(car.reviewIndex+1))|number_format('2') }} %</p>
                {% endif %}
            </span>
        </div>

        <ul class="list-group list-group-flush card-text">
            {% if car.generation %}
                <li class="list-group-item card-item">
                    <span>{{ 'Generation'|trans }}</span>
                    <span>{{ car.generation }}</span>
                </li>
            {% endif %}
            <li class="list-group-item card-item">
                <span>{{ 'Manufactured in'|trans }}</span>
                <span>{{ car.manufactured }}</span>
            </li>
            <li class="list-group-item card-item">
                <span>{{ 'Driven axle'|trans }}</span>
                <span>{{ car.drivenAxle }}</span>
            </li>
            <li class="list-group-item card-item">
                <span>{{ 'Seat count'|trans }}</span>
                <span>{{ car.seatCount }}</span>
            </li>
        </ul>
        <div class="d-flex justify-content-between">
            <span>
                <a href="
                        {% if dbal %}{{ path('details.manufacturer', {'id': car.manufacturer_id}) }}
                        {% else %}{{ path('details.manufacturer', {'id': car.manufacturer.id}) }}{% endif %}"
                   class="card-link">Manufacturer</a>
                <a href="{% if dbal %}{{ path('details.engine', {'id': car.engine_id}) }}
                        {% else %}{{ path('details.engine', {'id': car.engine.id}) }}{% endif %}"
                   class="card-link">Engine</a>
            </span>
            {% if app.user != null %}
                {% if dbal and app.user.id is same as(car.addedBy) %}
                    {% set editable = true %}
                {% elseif not dbal and app.user is same as(car.addedBy) %}
                    {% set editable = true %}
                {% else %}
                    {% set editable = false %}
                {% endif %}
                {% if editable %}
                    <a class="card-link text-danger" href="{{ path('edit.car', {'id': car.id}) }}">Edit</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
</div>

templates/components/cards/engine.html.twig
<ul class="info-list-group">
    {% if engine.name != null%}
        <li>
            <h3>Engine code:</h3>
            <h3><a href="{{ path('details.engine', {'id': engine.id}) }}">{{ engine.name }}</a></h3>
        </li>
    {% endif %}
    <li>
        <div class="row justify-content-between text-center w-100">
            <div class="col-4 d-flex flex-column">
                <span>Fuel:</span>
                <span><strong>{{ engine.fuel }}</strong></span>
            </div>
            <div class="col-4 d-flex flex-column">
                <span>Number of cylinders:</span>
                <span><strong>{{ engine.numberOfCylinders }}</strong></span>
            </div>
            <div class="col-4 d-flex flex-column">
                <span>Aspiration:</span>
                <span><strong {% if engine.aspiration != 'NA' %}class="text-danger"{% endif %} ">{{ engine.aspiration }}</strong></span>
            </div>
        </div>
    </li>
    <li>
        <div class="row justify-content-between text-center w-100">
            <div class="col-4 d-flex flex-column">
                <span>Engine size:</span>
                <span><strong>{{ engine.size }}</strong> <small>cm³</small></span>
            </div>
            <div class="col-4 d-flex flex-column">
                <span>Max power:</span>
                <span><strong class="text-danger">{{ engine.maxPower }}</strong> <small>kW</small></span>
            </div>
            <div class="col-4 d-flex flex-column">
                <span>Max torque:</span>
                <span><strong class="text-primary">{{ engine.maxTorque }}</strong> <small>Nm</small></span>
            </div>
        </div>
    </li>
</ul>