src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OneToMany;
use Symfony\Component\Serializer\Annotation\Ignore;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CarRepository::class)
 */
class Car
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer", length=128, options={"unsigned": true})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer", length=4)
     * @Assert\Range(
     *     max="now year",
     *     min=1850
     * )
     */
    private $manufactured;

    /**
     * @OneToMany(targetEntity="App\Entity\CarReview", mappedBy="car")
     */
    private $reviews;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $generation;

    /**
     * @ORM\Column(type="string", length=3)
     * @Assert\Choice({"FWD", "RWD", "AWD"})
     */
    private $driven_axle;

    /**
     * @ORM\Column(type="integer", length=2)
     */
    private $seat_count;

    /**
     * @ORM\ManyToOne(targetEntity=Manufacturer::class, inversedBy="cars")
     * @ORM\JoinColumn(nullable=false)
     */
    private $manufacturer;

    /**
     * @ORM\ManyToOne(targetEntity=BodyStyle::class, inversedBy="cars")
     * @ORM\JoinColumn(nullable=false)
     */
    private $body_style;

    /**
     * @ORM\ManyToOne(targetEntity=Engine::class, inversedBy="cars")
     * @ORM\JoinColumn(nullable=false)
     */
    private $engine;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="cars")
     * @ORM\JoinColumn(nullable=false)
     */
    private $added_by;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="car", orphanRemoval=true)
     * @Ignore()
     */
    private $images;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->reviews = new ArrayCollection();
    }

    public function getReviews()
    {
        return $this->reviews;
    }

    public function removeReview(CarReview $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getCar() === $this) {
                $review->setCar(null);
            }
        }

        return $this;
    }

    public function addReview(CarReview $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setCar($this);
        }

        return $this;
    }

    public function getReviewIndex(): float
    {
        $sum = 0;
        $count = 0;
        foreach ($this->getReviews() as $review) {
            $sum += $review->getValue();
            $count++;
        }
        if ($count === 0) return 0;
        return ($sum/$count);
    }


    public function getId(): ?int
    {
        return $this->id;
    }


    public function getGeneration(): ?string
    {
        return $this->generation;
    }

    public function setGeneration(?string $generation): self
    {
        $this->generation = $generation;

        return $this;
    }

    public function getDrivenAxle(): ?string
    {
        return $this->driven_axle;
    }

    public function setDrivenAxle(string $driven_axle): self
    {
        $this->driven_axle = $driven_axle;

        return $this;
    }

    public function getSeatCount(): ?int
    {
        return $this->seat_count;
    }

    public function setSeatCount(int $seat_count): self
    {
        $this->seat_count = $seat_count;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getManufacturer(): ?Manufacturer
    {
        return $this->manufacturer;
    }

    public function setManufacturer(?Manufacturer $manufacturer): self
    {
        $this->manufacturer = $manufacturer;

        return $this;
    }

    public function getBodyStyle(): ?BodyStyle
    {
        return $this->body_style;
    }

    public function setBodyStyle(?BodyStyle $body_style): self
    {
        $this->body_style = $body_style;

        return $this;
    }

    public function getEngine(): ?Engine
    {
        return $this->engine;
    }

    public function setEngine(?Engine $engine): self
    {
        $this->engine = $engine;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getManufactured()
    {
        return $this->manufactured;
    }

    /**
     * @param mixed $manufactured
     */
    public function setManufactured($manufactured): void
    {
        $this->manufactured = $manufactured;
    }

    public function getAddedBy(): ?User
    {
        return $this->added_by;
    }

    public function setAddedBy(?User $added_by): self
    {
        $this->added_by = $added_by;

        return $this;
    }

    public function __toString(): string
    {
        return $this->manufacturer->getName() . ' ' . $this->getName();
    }

    /**
     * @return Collection<int, Image>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setCar($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getCar() === $this) {
                $image->setCar(null);
            }
        }

        return $this;
    }
}

src/Controller/DetailsController.php
<?php

namespace App\Controller;

use App\Repository\CarRepository;
use App\Repository\EngineRepository;
use App\Repository\ManufacturerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route(name="details.")
 */
class DetailsController extends AbstractController
{
    /**
     * @Route(path="/car/{id}", name="car")
     */
    public function car(int $id, CarRepository $repo): Response
    {
        $car = $repo->find($id);
        return $this->render('pages/details/car.html.twig', [
            'car' => $car
        ]);
    }

    /**
     * @Route(path="/manufacturer/{id}", name="manufacturer")
     */
    public function manufacturer(int $id, ManufacturerRepository $repo): Response
    {
        $manufacturer = $repo->find($id);
        return $this->render('pages/details/manufacturer.html.twig', [
            'manufacturer' => $manufacturer
        ]);
    }

    /**
     * @Route(path="/engine/{id}", name="engine")
     */
    public function engine(int $id, EngineRepository $repo): Response
    {
        $engine = $repo->find($id);
        return $this->render('pages/details/engine.html.twig', [
            'engine' => $engine
        ]);
    }
}

templates/pages/details/car.html.twig
{% extends 'base.html.twig' %}

{% block title %}Car detail{% endblock %}

{% block body %}
    <div class="container-fluid my-3">
    {% if car %}
    <div class="row w-100 justify-content-center">
        <div class="col-lg-8">
            {# Car details #}
            <div class="w-100 mb-5">
                <div class="d-flex flex-row justify-content-between w-100">
                    <h3>Car:</h3>
                    <span class="text-center">
                        Reviews: <br />
                        <strong>{{ (50*(car.reviewIndex+1))|number_format(2) }} %</strong>
                    </span>
                    <a href="{{ path('edit.car', {'id': car.id}) }}"
                       class="btn btn-danger"
                    >
                        <i class="fa-solid fa-pencil"></i>
                    </a>
                </div>
                <hr/>
                <ul class="info-list-group mb-5">
                    <li>
                        <h3>Manufacturer:</h3>
                        <h3><a href="{{ path('details.manufacturer', {'id': car.manufacturer.id}) }}">{{ car.manufacturer }}</a></h3>
                    </li>
                    <li>
                        <h5>Name:</h5>
                        <h5>{{ car.name }}</h5>
                    </li>
                    <li>
                        <div class="row justify-content-center text-center w-100">
                            {% if car.generation != null %}
                            <div class="col-4 d-flex flex-column">
                                <span>Generation:</span>
                                <span><strong>{{ car.generation }}</strong></span>
                            </div>
                            {% endif %}
                            <div class="col-4 d-flex flex-column">
                                <span>Body style:</span>
                                <span><strong>{{ car.bodyStyle.name }}</strong></span>
                            </div>
                            <div class="col-4 d-flex flex-column">
                                <span>Driven axle:</span>
                                <span><strong>{{ car.drivenAxle }}</strong></span>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="row justify-content-center text-center w-100">
                            <div class="col-4 d-flex flex-column">
                                <span>Seat count:</span>
                                <span><strong>{{ car.seatCount }}</strong></span>
                            </div>
                            <div class="col-4 d-flex flex-column">
                                <span>Owner:</span>
                                <span><strong>{{ car.addedBy.email }}</strong></span>
                            </div>
                        </div>
                    </li>
                </ul>
                {# Engine details #}
                <div class="w-100">
                    <h3>Engine:</h3>
                    <hr/>
                    {% include 'components/cards/engine.html.twig' with {'engine': car.engine} %}
                </div>
            </div>
            {# Images #}
            {% if car.images is not empty %}
                <h3>Images:</h3>
                <hr />
                <div class="d-block mb-3 card">
                    <div class="card-body">
                        <div class="card-text">
                            {% for image in car.images %}
                                <div class="position-relative text-center">
                                    <a href="{{ upload_image_dir }}/{{ image.fileName }}" target="_blank">
                                        <img class="img-thumbnail"
                                             src="{{ upload_image_dir }}/{{ image.fileName }}"
                                             alt="{{ image.fileName }}"
                                        >
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endif %}
            {% else %}
                <h1 class="display-1 w-100 text-center text-danger">Car with this ID does not exist!</h1>
                <a href="{{ path('index') }}"><h3 class="w-100 text-center">To index!</h3></a>
            {% endif %}


        </div>
    </div>
{% endblock %}

templates/pages/details/engine.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ engine }}{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row my-3 justify-content-center">
            <div class="col-lg-6">
                {% include 'components/cards/engine.html.twig' with {'engine': engine} %}
            </div>
        </div>
        <div class="row my-3 px-5">
            <span class="w-100 text-left display-5">In cars:</span>
            <hr />
            {% include 'components/car_table.html.twig' with {'cars': engine.cars} %}
        </div>
    </div>
{% endblock %}

templates/pages/details/manufacturer.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ manufacturer.name }}{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row my-3">
            <h1 class="w-100 text-center display-1">{{ manufacturer.name }}</h1>
        </div>
        <div class="row my-3 px-5">
            <table class="table table-hover">
                <thead>
                <tr>
                    <td>Name</td>
                    <td>Generation</td>
                    <td>Manufactured</td>
                    <td>Driven axle</td>
                    <td>Seat count</td>
                </tr>
                </thead>
                <tbody>
                {% for car in manufacturer.cars %}
                    <tr data-href="{{ path('details.car', {'id': car.id}) }}">
                        <td>{{ car.name }}</td>
                        <td>{% if car.generation %}{{ car.generation }}{% endif %}</td>
                        <td>{{ car.manufactured }}</td>
                        <td>{{ car.drivenAxle }}</td>
                        <td>{{ car.seatCount }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}